// src/components/project-documents/index.tsx
"use client";

import SiteHeader from "@/layouts/SiteHeader";
import SiteFooterBlock from "@/layouts/SiteFooterBlock";

/** Document hubs from https://prestigeone.ae/project-documents/ */
const documentItems = [
  {
    title: "FAUCHON Résidences Project Documents",
    href: "/project-documents/fauchon-residences-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/fauchon/fauchon-banner.webp",
  },
  {
    title: "Hilton Project Documents",
    href: "/project-documents/hilton-residences-dubai-maritime-city-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/hilton/HILTON-NIGHT-VIEW-1.webp",
  },
  {
    title: "Sanctuary Project Documents",
    href: "/project-documents/the-sanctuary-by-prestige-one-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/sanctuary/sanctuary-residential-exterior-view.webp",
  },
  {
    title: "Vista Project Documents",
    href: "/project-documents/vista-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/vista/vista.webp",
  },
  {
    title: "The Residence Project Documents",
    href: "/project-documents/the-residence-spa-tcs/",
    thumbnail:
      "/assets/images/v2/project-featured-images/residence/THE-RESIDENCE.webp",
  },
  {
    title: "Seaside Project Documents",
    href: "/project-documents/seaside-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/seaside/seaside-featured-image.webp",
  },
  {
    title: "Golf Residences Project Documents",
    href: "/project-documents/golf-residences-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/golf/The-Place-Banner.webp",
  },
  {
    title: "The Waterway Project Documents",
    href: "/project-documents/the-waterway-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/waterway/Waterway-pic-2.webp",
  },
  {
    title: "Parkway Project Documents",
    href: "/project-documents/parkway-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/parkway/parkway.webp",
  },
  {
    title: "The One Project Documents",
    href: "/project-documents/the-one-spa-tcs/",
    thumbnail:
      "/assets/images/v2/project-featured-images/one/the-one.webp",
  },
  {
    title: "The Boulevard Project Documents",
    href: "/project-documents/the-boulevard-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/boulevard/boulevard.webp",
  },
  {
    title: "Coastal Haven Project Documents",
    href: "/project-documents/coastal-haven-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/coastal-haven/Coastal-Haven.webp",
  },
  {
    title: "Luxury Canal Project Documents",
    href: "/project-documents/luxury-canal-spa-tcs/",
    thumbnail: "/assets/images/v2/project-featured-images/luxury-canal/luxury-canal.webp",
  },
  {
    title: "Berkeley Square Project Documents",
    href: "/project-documents/berkeley-square-spa-tcs/",
    thumbnail:
      "/assets/images/v2/project-featured-images/berkeley/Berkeley-Square-North.webp",
  },
];

const ProjectDocumentsPage = () => {
  return (
    <>
      <SiteHeader />

      <section className="po-project-docs-hero">
        <div className="container">
          <div className="po-project-docs-hero-inner text-center">
            <p className="po-project-docs-kicker">Prestige One Developments</p>
            <h1>Project Documents</h1>
            <p>
              Access project-specific documents and resources. Select a development below to view
              available materials on our official portal.
            </p>
          </div>
        </div>
      </section>

      <section className="po-project-docs-section">
        <div className="container">
          <ul className="po-project-docs-list">
            {documentItems.map((item) => (
              <li key={item.href} className="po-project-docs-item">
                <a href={item.href} className="po-project-docs-link">
                  <span className="po-project-docs-thumb-wrap">
                    <img
                      src={item.thumbnail}
                      alt=""
                      className="po-project-docs-thumb"
                      loading="lazy"
                      decoding="async"
                    />
                  </span>
                  <span className="po-project-docs-title">{item.title}</span>
                  <span className="po-project-docs-cta">
                    <span>Find Out More</span>
                    <svg viewBox="0 0 24 24" aria-hidden="true" width="18" height="18">
                      <path
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="1.6"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M7 17L17 7M17 7H9M17 7V15"
                      />
                    </svg>
                  </span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <SiteFooterBlock />
    </>
  );
};

export default ProjectDocumentsPage;

// app/pages/project-documents/index.vue
<template>
  <div>
    <common-magic-cursor />
    <nuxt-layout name="layout-one">
      <div id="smooth-wrapper">
        <div id="smooth-content">
          <main class="prestige-page">
            <prestige-page-hero
              class="po-project-docs-page-hero"
              eyebrow="Prestige One Developments"
              title="Project Documents"
              lead="Access project-specific documents and resources. Select a development below to view available materials on our official portal."
              image="/assets/project-featured-images/sliders/boulevard.webp"
            />

            <section class="po-project-docs-section">
              <div class="container container-1430">
                <ul class="po-project-docs-list">
                  <li v-for="hub in projectDocumentHubs" :key="hub.slug" class="po-project-docs-item tp_fade_anim">
                    <NuxtLink :to="`/project-documents/${hub.slug}`" class="po-project-docs-link">
                      <span class="po-project-docs-thumb-wrap">
                        <img :src="hub.thumbnail" alt="" class="po-project-docs-thumb" loading="lazy" decoding="async">
                      </span>
                      <span class="po-project-docs-title">{{ hub.listTitle }}</span>
                      <span class="po-project-docs-cta">
                        <span>Find Out More</span>
                        <svg viewBox="0 0 24 24" aria-hidden="true" width="18" height="18">
                          <path fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" d="M7 17L17 7M17 7H9M17 7V15" />
                        </svg>
                      </span>
                    </NuxtLink>
                  </li>
                </ul>
              </div>
            </section>
          </main>
          <prestige-footer-digital-marketing />
        </div>
      </div>
    </nuxt-layout>
  </div>
</template>

<script setup lang="ts">
import { projectDocumentHubs } from "~/data/project-document-hubs";

definePageMeta({ layout: false });
useSeoMeta({
  title: "Project Documents | Prestige One",
  description: "Access project-specific documents and resources from Prestige One Developments.",
});

usePrestigePage({ hero: false });
</script>
