// src/app/broker-registration/[slug]/page.tsx
import { notFound } from "next/navigation";
import BrokerRegistrationDetailPage from "@/components/broker-registration/BrokerRegistrationDetailPage";
import {
  BROKER_REGISTRATION_PAGE_CONTENT,
  BROKER_REGISTRATION_SLUGS,
  isBrokerRegistrationSlug,
} from "@/data/broker-registration";
import Wrapper from "@/layouts/Wrapper";

export function generateStaticParams() {
  return BROKER_REGISTRATION_SLUGS.map((slug) => ({ slug }));
}

type PageProps = {
  params: Promise<{ slug: string }>;
};

export async function generateMetadata({ params }: PageProps) {
  const { slug } = await params;
  if (!isBrokerRegistrationSlug(slug)) {
    return { title: "Broker registration | Prestige One Developments" };
  }
  const { heroTitle } = BROKER_REGISTRATION_PAGE_CONTENT[slug];
  return {
    title: `${heroTitle} | Prestige One Developments`,
    description: `Broker registration — ${heroTitle}. Prestige One Developments.`,
  };
}

export default async function BrokerRegistrationSlugRoute({ params }: PageProps) {
  const { slug } = await params;
  if (!isBrokerRegistrationSlug(slug)) {
    notFound();
  }
  const content = BROKER_REGISTRATION_PAGE_CONTENT[slug];

  return (
    <Wrapper>
      <BrokerRegistrationDetailPage slug={slug} {...content} />
    </Wrapper>
  );
}

// app/pages/broker-registration/[slug].vue
<template>
  <div>
    <common-magic-cursor />
    <nuxt-layout name="layout-one">
      <div id="smooth-wrapper">
        <div id="smooth-content">
          <prestige-broker-registration-detail :slug="slug" :content="content" />
          <prestige-footer-digital-marketing />
        </div>
      </div>
    </nuxt-layout>
  </div>
</template>

<script setup lang="ts">
import {
  brokerRegistrationPageContent,
  isBrokerRegistrationSlug,
} from "~/data/broker-registration";

const route = useRoute();
const routeSlug = String(route.params.slug ?? "");

if (!isBrokerRegistrationSlug(routeSlug)) {
  throw createError({ statusCode: 404, statusMessage: "Registration page not found" });
}

const slug = routeSlug;
const content = brokerRegistrationPageContent[slug];

definePageMeta({ layout: false });
useSeoMeta({
  title: `${content.heroTitle} | Prestige One Developments`,
  description: `Broker registration — ${content.heroTitle}. Prestige One Developments.`,
});
usePrestigePage({ hero: false });
</script>
